//! Model-agnostic text utilities shared by the inference trees.
//!
//! Everything here answers a question about *text*, not about a model. Nothing in
//! this crate may name a model, a layer, a weight, or a checkpoint.
//!
//! # The boundary rule
//!
//! A module belongs here when it would be unchanged if every model in the
//! repository were replaced by a different architecture. The test is mechanical:
//! the crate must not depend on any model, layer or loader type, and it must not
//! acquire such a dependency later.
//!
//! | Module | Why it is model-agnostic |
//! |---|---|
//! | [`pyjson`] | Implements the semantics of Python's `json`, not of a model. |
//! | [`unicode_gc`] | General-category lookups and NFC over generated tables. |
//! | [`unicode_tables`] | The tables themselves, generated from `unicodedata`. |
//!
//! # What does not belong here
//!
//! Three neighbours are deliberately *not* in this crate, and each has a reason:
//!
//! * **Chat templates.** A template is model-specific by definition; a transcription
//!   of one model's Jinja template is not shared by a different model's.
//! * **Tokenizer engines.** These belong to a tokenizer *family* (byte-level BPE,
//!   trie longest-match), not to all models. Sharing across families would require
//!   guessing at unseen pre-tokenizer regexes, which turns a loud error into a
//!   silent mis-tokenization.
//! * **safetensors readers.** Each consumer's reader exists for its own purpose
//!   (product, I/O-cost measurement, self-contained validation), and sharing one
//!   would destroy the reason for the others.
//!
//! # Verification
//!
//! Moving a module here must not change behaviour. The corpora that verify the
//! consumers (`tok_corpus/`, `chat_corpus.json`, `sample_corpus.json`) stay
//! generated by the independent Python reference and are never produced by this
//! crate. Sharing code is safe precisely because the *oracle* stays independent.

pub mod pyjson;
pub mod unicode_gc;
pub mod unicode_tables;
